import Head from "next/head"

export const Layout = ({title, children}) => {
    return (
        <>
            <Head>
                <title>Three Scene | {title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className='app'>{children}</main>
        </>
    )
}
